### ISSUE TITLE
msiをリネームして同じフォルダにしていただけないでしょうか

### ISSUE THREAD

**Issue by coexe** [nathancorvussolis/skkime-archive#1]
まとめてくださってありがとうございます。
一点要望なのですが、SKKIME改だけ大量に別フォルダになってるのがなんか不憫なのでmsiの末尾に「_年月日」、例えば
	skkime15a_64bit_20170404.msi
みたいな感じでリネームして、同じ場所に重ね置きできるようにしていただけると嬉しいのですが、名前変更は可能でしょうか……
こちらが今後配布するファイルはこの形式にしておこうと思ってます

**Comment by nathancorvussolis** [comment]
了解です。後程整理します。

**Comment by nathancorvussolis** [comment]
しました！

**Comment by coexe** [comment]
お手数かけました。迅速な対応ありがとうございます！
